/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-06-16 01:28:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.css;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class module_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- portfolio section -->\r\n");
      out.write("\t\t\t<section id=\"portfolio\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sec-title text-center wow animated fadeInDown\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>S2 Module</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>차의 전복, 급정거를 빠르게 감지하여 위치정보를 전송합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"project-wrapper wow animated fadeInUp\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"resources/bootstrap3.3.5/img/portfolio/size.png\" class=\"img-responsive\" alt=\"width 8mm * length 8.5mm * height 5.7mm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"mask\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Size</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>width 8mm * length 8.5mm * height 5.7mm<br></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"external\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"fancybox\" title=\"Size\" data-fancybox-group=\"works\" href=\"resources/bootstrap3.3.5/img/portfolio/size.png\"><i class=\"fa fa-search\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"resources/bootstrap3.3.5/img/portfolio/modules.png\" class=\"img-responsive\" alt=\"Grove-IMU 9DOF v2.0, LED, Speaker, GY-GPS6MV2, FSR, ESP8266\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"mask\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Modules</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Grove-IMU 9DOF v2.0, LED, Speaker, GY-GPS6MV2, FSR, ESP8266</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"external\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"fancybox\" title=\"Modules\" href=\"resources/bootstrap3.3.5/img/portfolio/modules.png\" data-fancybox-group=\"works\" ><i class=\"fa fa-search\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"resources/bootstrap3.3.5/img/portfolio/pla_usb.png\" class=\"img-responsive\" alt=\"Material: PLA, Charging type: USB 2.0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"mask\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Material, Charging type</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Material: PLA, Charging type: USB 2.0</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"external\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"fancybox\" title=\"Material, Charging type\" data-fancybox-group=\"works\" href=\"resources/bootstrap3.3.5/img/portfolio/pla_usb.png\"><i class=\"fa fa-search\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"resources/bootstrap3.3.5/img/portfolio/gyro.png\" class=\"img-responsive\" alt=\"The gyro sensor Grove-IMU 9DOF v2.0 detects sudden inclination of the vehicle and announces a rollover accident.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"mask\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Grove-IMU 9DOF v2.0</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>The gyro sensor Grove-IMU 9DOF v2.0 detects sudden inclination of the vehicle and announces a rollover accident.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"external\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"fancybox\" title=\"Grove-IMU 9DOF v2.0\" data-fancybox-group=\"works\" href=\"resources/bootstrap3.3.5/img/portfolio/gyro.png\"><i class=\"fa fa-search\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"resources/bootstrap3.3.5/img/portfolio/pressure.png\" class=\"img-responsive\" alt=\"The FSR pressure sensor detects sudden stop due to shock.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"mask\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>FSR (Force sensitive resistor)</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>The FSR pressure sensor detects sudden stop due to shock.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"external\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"fancybox\" title=\"FSR (Force sensitive resistor)\" data-fancybox-group=\"works\" href=\"resources/bootstrap3.3.5/img/portfolio/pressure.png\"><i class=\"fa fa-search\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"portfolio-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"resources/bootstrap3.3.5/img/portfolio/wifi_gps.png\" class=\"img-responsive\" alt=\"The GY-GPS6MV2 receives the vehicle's location information and immediately sends it through the ESP8266 wifi device.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<figcaption class=\"mask\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>GY-GPS6MV2, ESP8266</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>The GY-GPS6MV2 receives the vehicle's location information and immediately sends it through the ESP8266 wifi device.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</figcaption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"external\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"fancybox\" title=\"GY-GPS6MV2, ESP8266\" data-fancybox-group=\"works\" href=\"resources/bootstrap3.3.5/img/portfolio/wifi_gps.png\"><i class=\"fa fa-search\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- end portfolio section -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
