/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-06-19 04:21:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.css;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class slider_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--\n");
      out.write("        Home Slider\n");
      out.write("        ==================================== -->\n");
      out.write("\n");
      out.write("<section id=\"home-slider\">\n");
      out.write("\t<div id=\"slider\" class=\"sl-slider-wrapper\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"sl-slider\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"sl-slide\" data-orientation=\"horizontal\"\n");
      out.write("\t\t\t\tdata-slice1-rotation=\"-25\" data-slice2-rotation=\"-25\"\n");
      out.write("\t\t\t\tdata-slice1-scale=\"2\" data-slice2-scale=\"2\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"bg-img bg-img-1\"></div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"slide-caption\">\n");
      out.write("\t\t\t\t\t<div class=\"caption-content\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"animated fadeInDown\">S2 Secondary Safe</h2>\n");
      out.write("\t\t\t\t\t\t<span class=\"animated fadeInDown\">신속한 사고감지 및 2차사고 방지 모듈입니다.</span>\n");
      out.write("\t\t\t\t\t\t<a href=\"#portfolio\" class=\"btn btn-blue btn-effect\">More</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"sl-slide\" data-orientation=\"vertical\"\n");
      out.write("\t\t\t\tdata-slice1-rotation=\"10\" data-slice2-rotation=\"-15\"\n");
      out.write("\t\t\t\tdata-slice1-scale=\"1.5\" data-slice2-scale=\"1.5\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"bg-img bg-img-2\"></div>\n");
      out.write("\t\t\t\t<div class=\"slide-caption\">\n");
      out.write("\t\t\t\t\t<div class=\"caption-content\">\n");
      out.write("\t\t\t\t\t\t<h2>S2 Secondary Safe</h2>\n");
      out.write("\t\t\t\t\t\t<span>오픈 API로 실시간 사고현황을 확인 할 수 있습니다.</span> <a href=\"#reference\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-blue btn-effect\">More</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"sl-slide\" data-orientation=\"horizontal\"\n");
      out.write("\t\t\t\tdata-slice1-rotation=\"3\" data-slice2-rotation=\"3\"\n");
      out.write("\t\t\t\tdata-slice1-scale=\"2\" data-slice2-scale=\"1\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"bg-img bg-img-3\"></div>\n");
      out.write("\t\t\t\t<div class=\"slide-caption\">\n");
      out.write("\t\t\t\t\t<div class=\"caption-content\">\n");
      out.write("\t\t\t\t\t\t<h2>S2 Secondary Safe</h2>\n");
      out.write("\t\t\t\t\t\t<span>사고현황을 지도로 확인 할 수 있습니다.</span> <a href=\"#google_map\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-blue btn-effect\">More</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /sl-slider -->\n");
      out.write("\n");
      out.write("\t\t<!-- \n");
      out.write("                <nav id=\"nav-arrows\" class=\"nav-arrows\">\n");
      out.write("                    <span class=\"nav-arrow-prev\">Previous</span>\n");
      out.write("                    <span class=\"nav-arrow-next\">Next</span>\n");
      out.write("                </nav>\n");
      out.write("                -->\n");
      out.write("\n");
      out.write("\t\t<nav id=\"nav-arrows\"\n");
      out.write("\t\t\tclass=\"nav-arrows hidden-xs hidden-sm visible-md visible-lg\">\n");
      out.write("\t\t\t<a href=\"javascript:;\" class=\"sl-prev\"> <i\n");
      out.write("\t\t\t\tclass=\"fa fa-angle-left fa-3x\"></i>\n");
      out.write("\t\t\t</a> <a href=\"javascript:;\" class=\"sl-next\"> <i\n");
      out.write("\t\t\t\tclass=\"fa fa-angle-right fa-3x\"></i>\n");
      out.write("\t\t\t</a>\n");
      out.write("\t\t</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<nav id=\"nav-dots\"\n");
      out.write("\t\t\tclass=\"nav-dots visible-xs visible-sm hidden-md hidden-lg\">\n");
      out.write("\t\t\t<span class=\"nav-dot-current\"></span> <span></span> <span></span>\n");
      out.write("\t\t</nav>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<!-- /slider-wrapper -->\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("        End Home SliderEnd\n");
      out.write("        ==================================== -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
